// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using productsAPI.Models;

#nullable disable

namespace productsAPI.Migrations
{
    [DbContext(typeof(ProductsContext))]
    partial class ProductsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("productsAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("ProductName")
                        .HasColumnType("text");

                    b.HasKey("ProductID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            IsActive = true,
                            Price = 20000m,
                            ProductName = "Telefon"
                        },
                        new
                        {
                            ProductID = 2,
                            IsActive = true,
                            Price = 3500m,
                            ProductName = "Klavye"
                        },
                        new
                        {
                            ProductID = 3,
                            IsActive = false,
                            Price = 45000m,
                            ProductName = "Bilgisayar"
                        },
                        new
                        {
                            ProductID = 4,
                            IsActive = true,
                            Price = 12000m,
                            ProductName = "Oyuncu Koltuğu"
                        },
                        new
                        {
                            ProductID = 5,
                            IsActive = true,
                            Price = 2500m,
                            ProductName = "Kulaklık"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
